version: "3.8"
services:
  backend:
    container_name: backend_ocr
    build:
      context: ./back/
      dockerfile: Dockerfile
    volumes:
      - ./back/:/go/src/
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

  frontend:
    container_name: frontend_ocr
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true